// Code generated by capnpc-go. DO NOT EDIT.

package serialization

import (
	capnp "zombiezen.com/go/capnproto2"
	text "zombiezen.com/go/capnproto2/encoding/text"
	schemas "zombiezen.com/go/capnproto2/schemas"
)

type StructCapnproto struct{ capnp.Struct }

// StructCapnproto_TypeID is the unique identifier for the type StructCapnproto.
const StructCapnproto_TypeID = 0xfd8784e879714b40

func NewStructCapnproto(s *capnp.Segment) (StructCapnproto, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return StructCapnproto{st}, err
}

func NewRootStructCapnproto(s *capnp.Segment) (StructCapnproto, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return StructCapnproto{st}, err
}

func ReadRootStructCapnproto(msg *capnp.Message) (StructCapnproto, error) {
	root, err := msg.RootPtr()
	return StructCapnproto{root.Struct()}, err
}

func (s StructCapnproto) String() string {
	str, _ := text.Marshal(0xfd8784e879714b40, s.Struct)
	return str
}

func (s StructCapnproto) Ts() int64 {
	return int64(s.Struct.Uint64(0))
}

func (s StructCapnproto) SetTs(v int64) {
	s.Struct.SetUint64(0, uint64(v))
}

func (s StructCapnproto) Tag() (string, error) {
	p, err := s.Struct.Ptr(0)
	return p.Text(), err
}

func (s StructCapnproto) HasTag() bool {
	p, err := s.Struct.Ptr(0)
	return p.IsValid() || err != nil
}

func (s StructCapnproto) TagBytes() ([]byte, error) {
	p, err := s.Struct.Ptr(0)
	return p.TextBytes(), err
}

func (s StructCapnproto) SetTag(v string) error {
	return s.Struct.SetText(0, v)
}

// StructCapnproto_List is a list of StructCapnproto.
type StructCapnproto_List struct{ capnp.List }

// NewStructCapnproto creates a new list of StructCapnproto.
func NewStructCapnproto_List(s *capnp.Segment, sz int32) (StructCapnproto_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1}, sz)
	return StructCapnproto_List{l}, err
}

func (s StructCapnproto_List) At(i int) StructCapnproto { return StructCapnproto{s.List.Struct(i)} }

func (s StructCapnproto_List) Set(i int, v StructCapnproto) error {
	return s.List.SetStruct(i, v.Struct)
}

func (s StructCapnproto_List) String() string {
	str, _ := text.MarshalList(0xfd8784e879714b40, s.List)
	return str
}

// StructCapnproto_Promise is a wrapper for a StructCapnproto promised by a client call.
type StructCapnproto_Promise struct{ *capnp.Pipeline }

func (p StructCapnproto_Promise) Struct() (StructCapnproto, error) {
	s, err := p.Pipeline.Struct()
	return StructCapnproto{s}, err
}

const schema_85d3acc39d94e0f8 = "x\xda\x12Ht`2d\xdd\xcf\xc8\xc0\x10(\xc2\xca" +
	"\xf6\xdf\xc1\xbb\xb0\xf2EK\xfb_\x86@yF\xc6\xff" +
	"?\x1eL\x99{x\xcd\xe5V\x06VFv\x06\x06\xc3" +
	"\xa3U\x8c\x827\xd9\x19\x18\x04\xaf\x963\xe8\xfe/N" +
	"-\xcaL\xcc\xc9\xacbI,\xc9\xcc\xcf\xd3ON," +
	"\xc8+(\xca/\xc97\xd2\x033\xad\x82K\x8aJ\x93" +
	"K\x9c\x13\x0b\xec!\xe2\x01\x8c\x8c\x81\x1c\xcc,\x0c\x0c" +
	",\x8c\x0c\x0c\x82\x9aR\x0c\x0c\x81*\xcc\x8c\x81\x06L" +
	"\x8c\x8c\x8c\"\x8c 1]%\x06\x86@\x0df\xc6@" +
	"\x13&F\xe6\x92bFV\x06&FV\x06F\xf6\x92" +
	"\xc4tF\x1e\x06&F\x1e\x06F@\x00\x00\x00\xff\xff" +
	"\xc1\xff,B"

func init() {
	schemas.Register(schema_85d3acc39d94e0f8,
		0xfd8784e879714b40)
}
