// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package serialization

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson1112f00eDecodeStashProstreamRuWsStreamSerialization(in *jlexer.Lexer, out *TestSerializationStruct) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "Ts":
			out.Ts = int64(in.Int64())
		case "Tag":
			out.Tag = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson1112f00eEncodeStashProstreamRuWsStreamSerialization(out *jwriter.Writer, in TestSerializationStruct) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"Ts\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int64(int64(in.Ts))
	}
	{
		const prefix string = ",\"Tag\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Tag))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v TestSerializationStruct) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson1112f00eEncodeStashProstreamRuWsStreamSerialization(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v TestSerializationStruct) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson1112f00eEncodeStashProstreamRuWsStreamSerialization(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *TestSerializationStruct) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson1112f00eDecodeStashProstreamRuWsStreamSerialization(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *TestSerializationStruct) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson1112f00eDecodeStashProstreamRuWsStreamSerialization(l, v)
}
